--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create bg
local bg = ccui.ImageView:create()
bg:ignoreContentAdaptWithSize(false)
bg:loadTexture("ui/lobby/image/Table.jpg",0)
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setTag(7)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
Layer:addChild(bg)

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor({r = 26, g = 26, b = 26})
Panel_1:setBackGroundColorOpacity(112)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(9)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
Layer:addChild(Panel_1)

--Create ListView_1
local ListView_1 = ccui.ListView:create()
ListView_1:setDirection(1)
ListView_1:setGravity(0)
ListView_1:ignoreContentAdaptWithSize(false)
ListView_1:setClippingEnabled(false)
ListView_1:setBackGroundColorType(1)
ListView_1:setBackGroundColor({r = 150, g = 150, b = 255})
ListView_1:setBackGroundColorOpacity(102)
ListView_1:setLayoutComponentEnabled(true)
ListView_1:setName("ListView_1")
ListView_1:setTag(10)
ListView_1:setCascadeColorEnabled(true)
ListView_1:setCascadeOpacityEnabled(true)
ListView_1:setPosition(61.2603, 325.7244)
layout = ccui.LayoutComponent:bindLayoutComponent(ListView_1)
layout:setPositionPercentX(0.0479)
layout:setPositionPercentY(0.4524)
layout:setPercentWidth(0.1563)
layout:setPercentHeight(0.2778)
layout:setSize({width = 200.0000, height = 200.0000})
layout:setLeftMargin(61.2603)
layout:setRightMargin(1018.7400)
layout:setTopMargin(194.2756)
layout:setBottomMargin(325.7244)
Panel_1:addChild(ListView_1)

--Create Button_1
local Button_1 = ccui.Button:create()
Button_1:ignoreContentAdaptWithSize(false)
Button_1:loadTextureNormal("Default/Button_Normal.png",0)
Button_1:loadTexturePressed("Default/Button_Press.png",0)
Button_1:loadTextureDisabled("Default/Button_Disable.png",0)
Button_1:setTitleFontSize(14)
Button_1:setTitleText("页签1")
Button_1:setTitleColor({r = 65, g = 65, b = 70})
Button_1:setScale9Enabled(true)
Button_1:setCapInsets({x = 15, y = 11, width = 16, height = 14})
Button_1:setLayoutComponentEnabled(true)
Button_1:setName("Button_1")
Button_1:setTag(8)
Button_1:setCascadeColorEnabled(true)
Button_1:setCascadeOpacityEnabled(true)
Button_1:setPosition(100.0000, 175.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.8750)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.2500)
layout:setSize({width = 200.0000, height = 50.0000})
layout:setBottomMargin(150.0000)
ListView_1:pushBackCustomItem(Button_1)

--Create Button_1_0
local Button_1_0 = ccui.Button:create()
Button_1_0:ignoreContentAdaptWithSize(false)
Button_1_0:loadTextureNormal("Default/Button_Normal.png",0)
Button_1_0:loadTexturePressed("Default/Button_Press.png",0)
Button_1_0:loadTextureDisabled("Default/Button_Disable.png",0)
Button_1_0:setTitleFontSize(14)
Button_1_0:setTitleText("页签1")
Button_1_0:setTitleColor({r = 65, g = 65, b = 70})
Button_1_0:setScale9Enabled(true)
Button_1_0:setCapInsets({x = 15, y = 11, width = 16, height = 14})
Button_1_0:setLayoutComponentEnabled(true)
Button_1_0:setName("Button_1_0")
Button_1_0:setLocalZOrder(1)
Button_1_0:setTag(11)
Button_1_0:setCascadeColorEnabled(true)
Button_1_0:setCascadeOpacityEnabled(true)
Button_1_0:setPosition(100.0000, 125.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_1_0)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6250)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.2500)
layout:setSize({width = 200.0000, height = 50.0000})
layout:setTopMargin(50.0000)
layout:setBottomMargin(100.0000)
ListView_1:pushBackCustomItem(Button_1_0)

--Create Button_1_1
local Button_1_1 = ccui.Button:create()
Button_1_1:ignoreContentAdaptWithSize(false)
Button_1_1:loadTextureNormal("Default/Button_Normal.png",0)
Button_1_1:loadTexturePressed("Default/Button_Press.png",0)
Button_1_1:loadTextureDisabled("Default/Button_Disable.png",0)
Button_1_1:setTitleFontSize(14)
Button_1_1:setTitleText("页签1")
Button_1_1:setTitleColor({r = 65, g = 65, b = 70})
Button_1_1:setScale9Enabled(true)
Button_1_1:setCapInsets({x = 15, y = 11, width = 16, height = 14})
Button_1_1:setLayoutComponentEnabled(true)
Button_1_1:setName("Button_1_1")
Button_1_1:setLocalZOrder(2)
Button_1_1:setTag(12)
Button_1_1:setCascadeColorEnabled(true)
Button_1_1:setCascadeOpacityEnabled(true)
Button_1_1:setPosition(100.0000, 75.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_1_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3750)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.2500)
layout:setSize({width = 200.0000, height = 50.0000})
layout:setTopMargin(100.0000)
layout:setBottomMargin(50.0000)
ListView_1:pushBackCustomItem(Button_1_1)

--Create Button_1_2
local Button_1_2 = ccui.Button:create()
Button_1_2:ignoreContentAdaptWithSize(false)
Button_1_2:loadTextureNormal("Default/Button_Normal.png",0)
Button_1_2:loadTexturePressed("Default/Button_Press.png",0)
Button_1_2:loadTextureDisabled("Default/Button_Disable.png",0)
Button_1_2:setTitleFontSize(14)
Button_1_2:setTitleText("页签1")
Button_1_2:setTitleColor({r = 65, g = 65, b = 70})
Button_1_2:setScale9Enabled(true)
Button_1_2:setCapInsets({x = 15, y = 11, width = 16, height = 14})
Button_1_2:setLayoutComponentEnabled(true)
Button_1_2:setName("Button_1_2")
Button_1_2:setLocalZOrder(3)
Button_1_2:setTag(13)
Button_1_2:setCascadeColorEnabled(true)
Button_1_2:setCascadeOpacityEnabled(true)
Button_1_2:setPosition(100.0000, 25.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_1_2)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1250)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.2500)
layout:setSize({width = 200.0000, height = 50.0000})
layout:setTopMargin(150.0000)
ListView_1:pushBackCustomItem(Button_1_2)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

